"""GEPA evaluator: takes a candidate AC3-Rewrite compaction prompt,
runs a small LiC eval, returns (accuracy, side_info).

Per-call: writes the candidate prompt to a temp file under
src/ctx_editor/strategies/prompts/, invokes `ctx-editor` on a fixed
subset, reads results.json, summarizes pass/fail.

Designed for GEPA single-task search mode (one fixed mini-eval per call).
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import time
from pathlib import Path
from typing import Any

CTX_EDITOR_ROOT = Path("/home/v-homatthew/ctx_editor")
PROMPTS_DIR = CTX_EDITOR_ROOT / "src" / "ctx_editor" / "strategies" / "prompts"
RUN_OUT_ROOT = CTX_EDITOR_ROOT / "outputs" / "_gepa_rewrite_evals"

# Fixed mini-eval subset (small for budget; math is where Rewrite has
# the closest gap to Reset, so any improvement should show up here).
EVAL_MODEL = "deepseek_v4_flash_foundry"
EVAL_LB = "multi_endpoint_foundry"
EVAL_TASK = "math_v2"
EVAL_DATA_FILE = "data/htn50_52_math_subset.json"
EVAL_CONV = 0
EVAL_LIMIT = 12
EVAL_MAX_CONCURRENT = 4
EVAL_TIMEOUT_SECS = 360


def _write_candidate(prompt_text: str) -> str:
    """Write candidate prompt to a content-addressed file. Returns base name."""
    h = hashlib.sha1(prompt_text.encode()).hexdigest()[:12]
    name = f"_gepa_cand_{h}"
    out = PROMPTS_DIR / f"{name}.txt"
    out.write_text(prompt_text)
    return name


def _make_experiment_config(prompt_name: str) -> str:
    """Write a Hydra experiment config that uses the given prompt name.

    Sets analyzer to v8 (parity-fixed) and points at the shared analysis
    cache so per-eval wall time stays ~1.5 min. open_ended_output=true
    so candidates produced by GEPA (seeded from v8/v9) wrap output in
    <new_context>...</new_context>.
    """
    name = f"_gepa_ac3_rewrite_{prompt_name}"
    cfg = f"""# Auto-generated by GEPA evaluator. Uses candidate prompt: {prompt_name}
name: {name}

strategy:
  _target_: ctx_editor.strategies.ContextCompactionStrategy
  compaction_model: ${{model.ctx_editor.model}}
  compaction_timeout: ${{oc.select:model.ctx_editor.timeout,60}}
  compaction_reasoning_effort: ${{oc.select:model.ctx_editor.reasoning_effort,null}}
  compaction_prompt: {prompt_name}
  open_ended_output: true
  min_turns: 1
  use_memory: false
  memory_target: system
  analyzer_prompt_version: v8
  analysis_cache_dir: outputs/analysis_cache
"""
    cfg_path = CTX_EDITOR_ROOT / "src" / "ctx_editor" / "config" / "experiment" / f"{name}.yaml"
    cfg_path.write_text(cfg)
    return name


def evaluate_candidate(prompt_text: str) -> tuple[float, dict[str, Any]]:
    """Run a mini-LiC eval with `prompt_text` as the rewrite prompt.

    Returns (accuracy in [0, 1], side_info dict).
    """
    prompt_name = _write_candidate(prompt_text)
    exp_name = _make_experiment_config(prompt_name)

    ts = int(time.time())
    run_name = f"{exp_name}_{ts}"
    out_dir = RUN_OUT_ROOT / run_name
    out_dir.parent.mkdir(parents=True, exist_ok=True)

    replay_source = f"data/valid_prefixes_htn50_52/{EVAL_MODEL}/{EVAL_TASK}/conv{EVAL_CONV}"

    cmd = [
        "ctx-editor",
        f"experiment={exp_name}",
        f"model={EVAL_MODEL}",
        f"load_balancer={EVAL_LB}",
        f"task={EVAL_TASK}",
        f"task.data_file={EVAL_DATA_FILE}",
        "user_mode=sharded",
        f"execution.max_concurrent={EVAL_MAX_CONCURRENT}",
        f"execution.replay_source={replay_source}",
        "execution.replay_turns=1",
        f"task.limit={EVAL_LIMIT}",
        f"experiment_name={run_name}",
        f"logging.output_dir={out_dir}",
        "metadata.branch=_gepa_rewrite_eval",
    ]

    t0 = time.time()
    try:
        proc = subprocess.run(
            cmd, cwd=str(CTX_EDITOR_ROOT),
            capture_output=True, text=True,
            timeout=EVAL_TIMEOUT_SECS,
        )
    except subprocess.TimeoutExpired:
        return 0.0, {"error": "subprocess timeout", "elapsed": time.time() - t0}
    elapsed = time.time() - t0

    if proc.returncode != 0:
        return 0.0, {
            "error": f"ctx-editor returned rc={proc.returncode}",
            "stderr_tail": (proc.stderr or "")[-1500:],
            "elapsed": elapsed,
        }

    results_path = out_dir / "results.json"
    if not results_path.exists():
        return 0.0, {"error": "results.json missing", "elapsed": elapsed}
    rows = json.load(open(results_path))
    if not rows:
        return 0.0, {"error": "results.json empty", "elapsed": elapsed}

    n_correct = sum(1 for r in rows if r.get("is_correct"))
    n_evaluated = sum(1 for r in rows if r.get("num_turns", 0) > 0)
    accuracy = n_correct / n_evaluated if n_evaluated > 0 else 0.0

    # Side info: a few illustrative failures (with extracted answer + last user)
    failures = [r for r in rows if not r.get("is_correct") and r.get("num_turns", 0) > 0][:5]
    failure_summaries = []
    for r in failures:
        failure_summaries.append({
            "sample_id": r.get("sample_id"),
            "extracted_answer": (r.get("extracted_answer") or "")[:300],
        })

    side = {
        "n_correct": n_correct,
        "n_evaluated": n_evaluated,
        "n_total": len(rows),
        "accuracy": accuracy,
        "elapsed_s": round(elapsed, 1),
        "failure_examples": failure_summaries,
        "run_dir": str(out_dir),
    }
    return accuracy, side


if __name__ == "__main__":
    # Quick smoke test using the v1 prompt
    v1_prompt = (PROMPTS_DIR / "context_compaction.txt").read_text()
    print("Smoke testing GEPA evaluator with v1 prompt...")
    score, info = evaluate_candidate(v1_prompt)
    print(f"score={score:.3f}")
    print(json.dumps(info, indent=2)[:1500])
